name: Test Compilazione # Action name
on:
  push:
    branches:
      - 'main'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Download file della Repo
        uses: actions/checkout@v3
      - name: Compilazione del file della Relazione
        uses: xu-cheng/latex-action@v3
        with: # insert here files to compile
          working_directory: Guide
          root_file: |
            Oliverian_Museums_Tour.tex
            Oliverian_Museums_Tour_Enlarged.tex
      - name: Ridenominazione files
        run: |
          mv Guide/Oliverian_Museums_Tour.pdf Guide/Guida_Musei_Oliveriani.pdf
          mv Guide/Oliverian_Museums_Tour_Enlarged.pdf Guide/Guida_Musei_Oliveriani_Ingrandita.pdf
      - name: Caricamento della Release temporanea
        uses: actions/upload-artifact@v3
        with: 
          name: Tour ai Musei Oliveriani
          path: |
            Guide/Guida_Musei_Oliveriani.pdf
            Guide/Guida_Musei_Oliveriani_Ingrandita.pdf
